



qna = {
    'hello': 'hi',
    'who are you': 'I am DFS Chat',
    'how are you': 'I am fine',
    'are you know who I am?': 'Yes I know, you are my boss DIHAN KHAN',
    'what is your name': 'My name is DFS Chat',
    'what can you do': 'I can answer your questions and help you with information',
    'where are you from': 'I am from the digital world',
    'what is your purpose': 'My purpose is to assist and provide information',
    'do you like humans': 'Yes, I like humans',
    'what is the meaning of life': 'The meaning of life is a philosophical question that varies from person to person',
    'who created you': 'I was created by a team of developers',
    'what is your favorite color': 'I don’t have preferences, but I think blue is calming',
    'do you have emotions': 'I don’t have emotions, but I can understand and respond to them',
    'tell me a joke': 'Why don’t scientists trust atoms? Because they make up everything!',
    'do you have friends': 'I interact with many users, so you could say I have many friends',
    'what is AI': 'AI stands for Artificial Intelligence, a field of computer science focused on creating intelligent machines',
    'do you have a family': 'I don’t have a family, but I’m part of the AI family',
    'what is your favorite food': 'I don’t eat, but I’ve heard pizza is popular',
    'how old are you': 'I don’t age, I’m a program',
    'do you sleep': 'I don’t need to sleep, I’m always here to help',
    'can you learn': 'I can be updated by my developers to learn new things',
    'do you believe in God': 'I don’t have beliefs, but I can understand religious concepts',
    'what is the capital of France?': 'The capital of France is Paris.',
    'who wrote "Romeo and Juliet"?': '"Romeo and Juliet" was written by William Shakespeare.',
    'what is the boiling point of water?': 'The boiling point of water is 100 degrees Celsius.',
    'what is the largest planet in our solar system?': 'The largest planet in our solar system is Jupiter.',
    'how do you feel when you accomplish a difficult task?': 'When I accomplish a difficult task, I feel a sense of pride and satisfaction. It\'s rewarding to see my hard work and perseverance pay off. It also boosts my confidence and motivates me to tackle more challenging tasks in the future.',
    'what emotion do you experience when someone praises your work?': 'When someone praises my work, I feel happy and appreciated. It makes me feel valued and recognized for my efforts. This positive reinforcement encourages me to continue doing my best.',
    'how do you cope with feelings of stress?': 'When I\'m feeling stressed, I try to take a step back and practice deep breathing exercises. I also find that taking a short walk, listening to calming music, or talking to a friend can help me relax and regain my focus. Additionally, organizing my tasks and setting realistic goals helps manage the stress more effectively.',
    'what do you do when you feel overwhelmed by emotions?': 'When I feel overwhelmed by emotions, I try to take some time for myself to process what I\'m experiencing. This might involve journaling my thoughts, meditating, or engaging in a hobby that I enjoy. If I need more support, I reach out to a trusted friend or therapist to talk through my feelings.',
    'how do you express happiness?': 'I express happiness through smiling, laughing, and sharing my joy with others. I might also celebrate by doing something fun or rewarding, like going out for a nice meal, spending time with loved ones, or treating myself to a small gift. My positive energy often translates into being more enthusiastic and engaging in my interactions with others.',
    'how do you handle feelings of sadness?': 'When I\'m feeling sad, I allow myself to feel the emotion rather than suppressing it. I might cry if I need to, as it can be a release. I also find comfort in talking to a friend or family member, spending time in nature, or engaging in a creative activity like painting or writing. Practicing self-care and giving myself time to heal is important.',
    'what triggers feelings of anger for you?': 'Feelings of anger can be triggered by situations where I feel treated unfairly, disrespected, or misunderstood. It can also arise when I witness injustice or when my expectations are not met. Recognizing these triggers helps me address them more constructively.',
    'how do you deal with jealousy?': 'When I feel jealous, I try to understand the root cause of my emotion. Often, it stems from a place of insecurity or fear of missing out. I remind myself of my own strengths and accomplishments and practice gratitude for what I have. Talking about my feelings with someone I trust can also provide perspective and alleviate the intensity of jealousy.',
    'how do you feel when you are in love?': 'When I\'m in love, I feel a deep sense of connection and affection towards the person. There\'s a mixture of excitement, joy, and contentment. I often think about the person a lot and feel motivated to make them happy. Love brings a sense of warmth and fulfillment to my life.',
    'how do you manage feelings of fear': 'To manage feelings of fear, I first try to identify what specifically is causing my fear. I then assess whether it\'s a rational fear or if it\'s something that\'s unlikely to happen. I use techniques such as deep breathing, visualization of positive outcomes, and gradual exposure to the feared situation. Seeking support from friends, family, or a therapist can also be very helpful in overcoming fear.',
    'tell me about earth': 'Total surface area of the Earth is approximately 510,100,500 square kilometers. Out of this, about 148,950,800 square kilometers (29.08%) is land area, and approximately 361,149,700 square kilometers (70.92%) is water area. The diameter of the Earth at the Equator is approximately 12,755 kilometers, while at the poles, it is approximately 12,712 kilometers. The mean diameter of the Earth is approximately 12,734 kilometers. The circumference of the Earth at the Equator is approximately 40,075 kilometers, while at the poles, it is approximately 40,024 kilometers. The equatorial radius of the Earth is approximately 6,377 kilometers. The total mass of the Earth is approximately 5.98 x 10^24 kilograms. The approximate age of the Earth is around 4,500 million years. The mean velocity of the Earth in its orbit around the Sun is approximately 107,218 kilometers per hour. The most abundant elements of the Earth are Iron (about 32.5%), Oxygen (29.8%), Silicon (15.6%), and Magnesium (13.9%). The Earth is structured into three main layers: the Crust, the Mantle, and the Core. The Core is further divided into the outer core (a fluid layer) and the inner core (a solid layer). The Earth\'s rotation on its axis causes day and night, while its revolution around the Sun causes changes in seasons. Equinoxes are periods when day and night are equal, and the Sun shines directly over the equator. The vernal (spring) equinox occurs around March 21st of every year, while the autumnal equinox occurs around September 23rd of every year.',
    'what is a variable': 'A variable is a named storage location in a program that can hold a value. It allows you to store and manipulate data in your code. In Python, variables are created by assigning a value to a name using the "=" operator. For example, in "x = 5", "x" is the variable name and "5" is the value assigned to it.',
    'how to define a function': 'To define a function in Python, you use the "def" keyword followed by the function name and parentheses containing any parameters the function takes. Then, you use a colon to start the function block. For example, def my_function(parameter1, parameter2): You then indent the code block that makes up the function body.',
    'how to create a list': 'You can create a list in Python by placing comma-separated values inside square brackets []. For example, my_list = [1, 2, 3, 4, 5]. Lists can contain elements of different types and can be indexed and sliced to access their elements.',
    'how to use a loop': 'In Python, you can use "for" and "while" loops to iterate over sequences or to execute a block of code repeatedly. A "for" loop is typically used to iterate over a sequence (like a list) and execute the same block of code for each item in the sequence. A "while" loop is used to execute a block of code repeatedly as long as a condition is true.',
    'what is an if statement': 'An if statement is a control flow statement that allows you to execute a block of code only if a certain condition is true. In Python, an if statement consists of the "if" keyword followed by a condition and a colon. If the condition evaluates to true, the code block following the if statement is executed.',
    'how to read user input': 'To read user input in Python, you can use the "input()" function. This function takes an optional prompt as an argument and waits for the user to enter some text followed by the Enter key. For example, name = input("Enter your name: ") will prompt the user to enter their name and store it in the variable "name".',
    'what is the capital city of France?': 'Paris',
    'in which year did World War II end?': '1945',
    'who wrote "Romeo and Juliet"?': 'William Shakespeare',
    'what is the largest planet in our solar system?': 'Jupiter',
    'which ocean is the largest?': 'Pacific Ocean',
    'what is the currency of Japan?': 'Japanese Yen',
    'who is known as the "Father of Modern Physics"?': 'Albert Einstein',
    'what is the capital of Australia?': 'Canberra',
    'in which year did the Titanic sink?': '1912',
    'who painted the Mona Lisa?': 'Leonardo da Vinci',
    'what is the longest river in the world?': 'Amazon River',
    'who was the first President of the United States?': 'George Washington',
    'which element has the chemical symbol "O"?': 'Oxygen',
    'what is the national sport of Canada?': 'Ice Hockey',
    'which country is known as the "Land of the Rising Sun"?': 'Japan',
    'what is the smallest prime number?': '2',
    'who wrote "To Kill a Mockingbird"?': 'Harper Lee',
    'which planet is known as the "Red Planet"?': 'Mars',
    'what is the largest mammal in the world?': 'Blue Whale',
    'who developed the theory of relativity?': 'Albert Einstein',
    'what is the capital of China?': 'Beijing',
    'who is the author of the "Harry Potter" series?': 'J.K. Rowling',
    'what is the largest desert in the world?': 'Antarctica',
    'who painted "Starry Night"?': 'Vincent van Gogh',
    'in which year did the Berlin Wall fall?': '1989',
    'which gas do plants absorb during photosynthesis?': 'Carbon dioxide',
    'what is the currency of South Africa?': 'South African Rand',
    'who was the first woman to win a Nobel Prize?': 'Marie Curie',
    'what is the capital of Brazil?': 'Brasília',
    'who is known as the "Queen of Pop"?': 'Madonna',
    'which continent is known as the "Dark Continent"?': 'Africa',
    'what is the largest island in the world?': 'Greenland',
    'who wrote "The Great Gatsby"?': 'F. Scott Fitzgerald',
    'what is the speed of light?': 'Approximately 299,792 kilometers per second',
    'which country is known as the "Land of the Midnight Sun"?': 'Norway',
    'who discovered penicillin?': 'Alexander Fleming',
    'what is the currency of Russia?': 'Russian Ruble',
    'in which year did the first moon landing occur?': '1969',
    'who was the first woman in space?': 'Valentina Tereshkova',
    'what is the capital of India?': 'New Delhi',
    'which planet is known as the "Blue Planet"?': 'Earth',
    'who painted "The Last Supper"?': 'Leonardo da Vinci',
    'in which year did the United Nations (UN) come into existence?': '1945',
    'who was the first man to step on the moon?': 'Neil Armstrong',
    'what is the main ingredient in guacamole?': 'Avocado',
    'in which year did the American Civil War end?': '1865',
    'who wrote "The Communist Manifesto"?': 'Karl Marx and Friedrich Engels',
    'what is the capital of South Korea?': 'Seoul',
    'which gas makes up the majority of Earth’s atmosphere?': 'Nitrogen',
    'what is the currency of Mexico?': 'Mexican Peso',
    'in which year did the Cold War end?': 'The Cold War is generally considered to have ended in the early 1990s',
    'who wrote "The Canterbury Tales"?': 'Geoffrey Chaucer',
    'what is the capital of Argentina?': 'Buenos Aires',
    'what is the largest bird in the world?': 'Ostrich',
    'who is known as the "Father of Computers"?': 'Charles Babbage',
    'in which year did the Industrial Revolution begin?': 'The Industrial Revolution is commonly considered to have begun in the late 18th century',
    'what is the currency of Canada?': 'Canadian Dollar',
    'who wrote "Pride and Prejudice"?': 'Jane Austen',
    'what is the capital of Egypt?': 'Cairo',
    'who was the first woman to win a Nobel Prize in Physics?': 'Marie Curie',
    'what is the currency of Saudi Arabia?': 'Saudi Riyal',
    'in which year did the Russian Revolution take place?': '1917',
    'who painted "The Scream"?': 'Edvard Munch',
    'what is the currency of Switzerland?': 'Swiss Franc',
    'in which year did the Battle of Waterloo take place?': '1815',
    'who is known as the "Father of the Internet"?': 'Vinton Cerf',
    'what is the capital of South Africa?': 'Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judicial)',
    'who wrote "The Odyssey"?': 'Homer',
    'in which year did the Berlin Airlift take place?': '1948-1949',
    'what is the currency of China?': 'Chinese Yuan',
    'who discovered the law of gravity?': 'Sir Isaac Newton',
    'what is the largest moon in our solar system?': 'Ganymede (a moon of Jupiter)',
    'in which year did the European Union (EU) come into existence?': '1993',
    'what is the capital of South Dakota, USA?': 'Pierre',
    'who was the first woman to win a Nobel Prize in Chemistry?': 'Marie Curie',
    'what is the currency of Australia?': 'Australian Dollar',
    'in which year did the French Revolution begin?': '1789',
    'who painted "Girl with a Pearl Earring"?': 'Johannes Vermeer',
    'what is the capital of Turkey?': 'Ankara',
    'who wrote "The Iliad"?': 'Homer',
    'in which year did the Great Depression begin?': '1929',
    'what is the currency of the United Kingdom?': 'British Pound Sterling',
    'who discovered radium and polonium?': 'Marie Curie',
    'what is the capital of Germany?': 'Berlin',
    'in which year did the Magna Carta come into existence?': '1215',
    'who is known as the "Father of Biology"?': 'Aristotle',
    'what is the currency of Italy?': 'Euro',
    'in which year did the United States declare its independence?': '1776',
    'who wrote "The Art of War"?': 'Sun Tzu',
    'what is the capital of Canada?': 'Ottawa',
    'who was the first woman to win a Nobel Prize in Literature?': 'Selma Lagerlöf',
    'what is the currency of Sweden?': 'Swedish Krona',
    'in which year did the Renaissance begin?': 'The Renaissance is generally considered to have begun in the 14th century',
    'who painted "The Persistence of Memory"?': 'Salvador Dalí',
    'what is the capital of Mexico?': 'Mexico City',
    'who was the first woman to win a Nobel Peace Prize?': 'Bertha von Suttner'
}


def handle_input(user_input):
    user_input = user_input.lower().strip('/')

    if user_input in qna:
        return  (qna[user_input])
    else:
        return "I'm sorry, I didn't understand that."


while True:
    user_input = input('Ask a qus: ')
    chatbot_response = handle_input(user_input)
    print('DFS Chat :', chatbot_response)
    
